config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: [ :new, :create]
  end
  resources :bookmarks, only: [ :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates_uniqueness_of :movie_id, :scope => [:list_id]
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmars, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmars, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
  validates :poster_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
    @movies = Movie.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    end
  end

  def edit
  end

  def update
    @list.update(params[:list])
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WATCH LIST</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col">
        <h3> Create a new list </h3>
         <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Action' %>
          <%= f.submit class: 'btn btn-info' %>
        <% end %>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=@movies.first.poster_url%>);">
  <div class="container">
    <h1><strong><%= @movies.first.title%></strong></h1>
  </div>
</div>

<div class="container">

  <div class="row my-list justify-content-between d-flex align-items-center">
    <div class="col-12 col-sm-4">
      <div class="titre"><h3>MY LISTS</h3></div>
    </div>
    <div class="col 12 col-sm-4">
      <div class="btn btn-new"><%= link_to "Create a movie list", new_list_path %></div>
    </div>
  </div>

  <div class="my-lists">
    <% @lists.each do |list| %>
      <h4><%= list.name.upcase %></h4>


      <%= link_to "See more", list_path(list), class: 'btn btn-more' %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class="container">
    <div class="row my-list justify-content-between d-flex align-items-center">
    <div class="col-12 col-sm-4">
      <div class="list-title"> <h2><%=@list.name.upcase%></h2></div>
    </div>
    <div class="col 12 col-sm-4">
      <div class="btn btn-new"><%= link_to "Add a movie", new_list_path %></div>
    </div>
  </div>

</div>


<%= link_to "Delete",
  list_path(@list), class: 'btn btn-info',
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_card.html.erb
  <div class="card">
        <div class="card-trip">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
          <div class="card-trip-infos">
            <div>
              <h2>Title here</h2>
              <p>Short description here!</p>
            </div>
            <h2 class="card-trip-pricing">£99.99</h2>
            <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
          </div>
        </div>
      </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1>WATCH LIST</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My Lists", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", new_list_path, class: "nav-link" %>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>